version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
