name: Deploy Frontend to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_PRODUCTION }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          directory: client
          file_name: .env.github
          fail_on_empty: false
          sort_keys: false

      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Build frontend
        run: |
          cd client
          npm run build:github

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: aws s3 sync client/build ${{ secrets.S3_STORAGE_PATH }}
