name: Build Backend image

on:
  workflow_dispatch:

env: 
  AWS_REGION: us-east-1
  IMAGE_NAME: soft-eol/backend
  ECR_IMAGE: ${{ secrets.ECR_URL }}/soft-eol/backend
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Save SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - run: |
          cd backend
          docker build -t ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha }} .            .
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha }} ${{ env.ECR_IMAGE }}:latest
          docker push ${{ env.ECR_IMAGE }}:${{ steps.vars.outputs.sha }}
          docker push ${{ env.ECR_IMAGE }}:latest
